name: merchant_ms
description: Merchant Manage System

version: 1.0.0+1
author: Nicole <nicolelihui@outlook.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.5.1
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^4.0.1
  #状态管理扩展-stream https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.5
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.0
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.4
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.1.8+1
  # 图片选择插件 https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.6.3
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.2
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.4.1
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.19+4
  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.8
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  # Json序列化 https://github.com/dart-lang/json_serializable
  json_annotation: ^3.0.1
  # 高德2D地图插件 https://github.com/simplezhli/flutter_2d_amap
  flutter_2d_amap:
    git:
      url: https://github.com/simplezhli/flutter_2d_amap.git
  # 扫码 https://github.com/apptreesoftware/flutter_barcode_reader
  barcode_scan:
    git:
      url: https://github.com/simplezhli/flutter_barcode_reader.git

  cupertino_icons: ^0.1.2

dev_dependencies:
  # Widget test
  flutter_test:
    sdk: flutter
  # Integration test
  flutter_driver:
    sdk: flutter
  # Unit test
  test: ^1.9.4
  # Json自动序列化
  build_runner: ^1.7.4
  json_serializable: ^3.2.5

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/data/
  - assets/images/
  - assets/images/home/
  - assets/images/store/
  - assets/images/state/
  - assets/images/order/
  - assets/images/order/dark/
  - assets/images/login/
  - assets/images/goods/
  - assets/images/shop/
  - assets/images/account/
  - assets/images/statistic/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
